name: rtd311
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pandoc
  - nbsphinx
  - jupyter
  - matplotlib
  - sphinx-copybutton
  - numpy
  - jax
  - jaxlib
  - diffmah
  - h5py